-- Linhas de produto: a mesma empresa vende mais de uma linha (importada, nacional…),
-- e cada linha tem os seus parâmetros, as suas alíquotas por estado, os seus
-- equipamentos e a sua tabela publicada. Um pedido é de uma linha só: a da versão
-- da tabela com que ele foi aberto.
-- Sem nome de esquema: cada empresa tem estas tabelas no esquema dela.

CREATE TABLE product_lines (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL CHECK (btrim(name) <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL CHECK (btrim(updated_by) <> '')
);
CREATE UNIQUE INDEX product_lines_name_idx ON product_lines (lower(btrim(name)));

-- O que já existe passa a ser a linha 1. O nome é só o inicial: a diretoria muda na tela.
INSERT INTO product_lines (id, name, updated_by) VALUES (1, 'Importada', 'migracao-0019');
SELECT setval(pg_get_serial_sequence('product_lines', 'id'), 1);

-- Parâmetros: uma linha da tabela por linha de produto (antes, uma só, com chave "true").
ALTER TABLE pricing_params DROP COLUMN id;
ALTER TABLE pricing_params ADD COLUMN line_id integer NOT NULL DEFAULT 1 REFERENCES product_lines (id);
ALTER TABLE pricing_params ALTER COLUMN line_id DROP DEFAULT;
ALTER TABLE pricing_params ADD PRIMARY KEY (line_id);

-- Alíquotas por estado: as 27 de cada linha.
ALTER TABLE state_tax_rates ADD COLUMN line_id integer NOT NULL DEFAULT 1 REFERENCES product_lines (id);
ALTER TABLE state_tax_rates ALTER COLUMN line_id DROP DEFAULT;
ALTER TABLE state_tax_rates DROP CONSTRAINT state_tax_rates_pkey;
ALTER TABLE state_tax_rates ADD PRIMARY KEY (line_id, uf);

-- Equipamento e versão publicada dizem de qual linha são. A numeração das versões
-- continua uma só na empresa: o pedido guarda o número e, por ele, a linha.
ALTER TABLE products ADD COLUMN line_id integer NOT NULL DEFAULT 1 REFERENCES product_lines (id);
CREATE INDEX products_line_id_idx ON products (line_id);
ALTER TABLE price_table_versions ADD COLUMN line_id integer NOT NULL DEFAULT 1 REFERENCES product_lines (id);
CREATE INDEX price_table_versions_line_id_idx ON price_table_versions (line_id, version DESC);
